version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: src/Stefanini.API/Dockerfile
    container_name: stefanini.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=sqlserver;Port=1433;Database=Stefanini;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - stefanini-network

  sqlserver:
    container_name: stefanini-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks:
      - stefanini-network

networks:
  stefanini-network:
    driver: bridge
