name: "Validate Build for Main"

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Stefanini.sln
        working-directory: ./Stefanini/Stefanini

      - name: Build solution
        run: dotnet build Stefanini.sln --no-restore --configuration Release
        working-directory: ./Stefanini/Stefanini

      - name: Run tests
        run: dotnet test Stefanini.sln --no-build --configuration Release --verbosity normal
        working-directory: ./Stefanini/Stefanini
