name: "Validate Build for Main"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debug
        run: |
          echo "Estrutura de arquivos:"
          ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./Stefanini/Stefanini.sln

      - name: Build solution
        run: dotnet build ./Stefanini/Stefanini.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./Stefanini/Stefanini.sln --no-build --configuration Release --verbosity normal
